module StimulusBuilder
  class ActionAttribute < Attribute
    def initialize: (*ActionDescriptor action_descriptors) -> void

    def +: (ActionAttribute action_attribute) -> ActionAttribute

    attr_reader action_descriptors: ::Array[ActionDescriptor]
  end
end
