module StimulusBuilder
  class ClassAttribute < Attribute
    @identifier: Controller
    @logical_name: ::String
    @klass: ::String

    def initialize: (Controller identifier, descriptive logical_name, ::String klass) -> void
  end
end
