module StimulusBuilder
  class Controller
    MODULE_SEPARATOR: String
    IDENTIFIER_SEPARATOR: String

    # FIXME: This should be a `String`. But Steep complains about passing the `&:dasherize` argument
    # to `map` below.
    @controller_name: untyped
    @element: Element

    def initialize: (descriptive controller_name, ElementRepresentable element) -> void

    def method_missing: (::String action_method, ?StimulusBuilder::Element element) -> Array[untyped]
      | (::String action_method, **untyped kargs) -> StimulusBuilder::Handler

    # FIXME: `event_name` should be a `descriptive`. But it complains about the `dasharize` method as
    # its provided by `ActiveSupport`, which is not available in RBS.
    def []: (untyped event_name) -> ::String

    def []=: (::String selector, Outlet outlet) -> void

    def to_s: () -> String

    def to_str: () -> String

    private def controller_identifier: () -> String
  end
end
