module StimulusBuilder
  class Outlet
    MODULE_SEPARATOR: ::String
    IDENTIFIER_SEPARATOR: ::String

    @name: ::String

    def initialize: (descriptive name) -> void

    def to_s: () -> String

    private def identifier: () -> String
  end
end
