module StimulusBuilder
  class Outlet
    MODULE_SEPARATOR: ::String
    IDENTIFIER_SEPARATOR: ::String

    # FIXME: This should be a `String`. But the RBS file for `ActiveSupport` is not available.
    @name: untyped

    def initialize: (descriptive name) -> void

    private def identifier: () -> String
  end
end
